# Generated by Django 4.1.7 on 2023-04-01 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarDates',
        ),
        migrations.DeleteModel(
            name='FeedInfo',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
