# Generated by Django 4.1.7 on 2023-04-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_delete_calendardates_delete_feedinfo_delete_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('exception_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calendar_dates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_publisher_name', models.TextField(blank=True, null=True)),
                ('feed_publisher_url', models.TextField(blank=True, null=True)),
                ('feed_lang', models.TextField(blank=True, null=True)),
                ('feed_version', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feed_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.TextField(blank=True, null=True)),
                ('note_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notes',
                'managed': False,
            },
        ),
    ]
